[[track]]
path = "http://d.liveatc.net/kmia3_atis_arr"
title = "KMIA ATIS Arrival"
artist = "Miami International"
album = "Live ATC"
genre = "ATIS"
realtime = true
[[track]]
path = "http://d.liveatc.net/ksfo_atis"
title = "KSFO ATIS"
artist = "San Francisco International"
album = "Live ATC"
genre = "ATIS"
realtime = true
