[[track]]
path = "http://d.liveatc.net/kmia3_twr"
title = "KMIA Tower"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_gnd"
title = "KMIA Ground"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_gnd2"
title = "KMIA Ground South (9/27/30)"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_11945"
title = "KMIA Approach 119.45"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_1205"
title = "KMIA Approach/Departure 120.5"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_12485"
title = "KMIA Approach 124.85"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_12575"
title = "KMIA Approach 125.75"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_133775"
title = "KMIA Approach KFLL 133.775"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_atis_arr"
title = "KMIA ATIS Arrival"
artist = "Miami International"
album = "Live ATC"
genre = "ATIS"
realtime = true
