[[track]]
path = "http://d.liveatc.net/egll_twr"
title = "EGLL Tower"
artist = "London Heathrow"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/eham01_twr_main1"
title = "EHAM Tower"
artist = "Amsterdam Schiphol"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/cyyz7"
title = "CYYZ Tower"
artist = "Toronto Pearson"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/cyvr1_gnd_twr"
title = "CYVR Ground/Tower"
artist = "Vancouver International"
album = "Live ATC"
genre = "ATC"
realtime = true
