[[track]]
path = "http://d.liveatc.net/kmia3_twr"
title = "KMIA Tower"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_gnd"
title = "KMIA Ground"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_gnd2"
title = "KMIA Ground South (9/27/30)"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_11945"
title = "KMIA Approach 119.45"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_1205"
title = "KMIA Approach/Departure 120.5"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_12485"
title = "KMIA Approach 124.85"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_12575"
title = "KMIA Approach 125.75"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_app_133775"
title = "KMIA Approach KFLL 133.775"
artist = "Miami International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kmia3_atis_arr"
title = "KMIA ATIS Arrival"
artist = "Miami International"
album = "Live ATC"
genre = "ATIS"
realtime = true
[[track]]
path = "http://d.liveatc.net/kjfk_twr"
title = "KJFK Tower"
artist = "John F. Kennedy"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kjfk9_s"
title = "KJFK Ground/Tower"
artist = "John F. Kennedy"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/klga_twr"
title = "KLGA Tower"
artist = "LaGuardia"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/kewr_twr"
title = "KEWR Tower"
artist = "Newark Liberty"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/klax_twr"
title = "KLAX Tower"
artist = "Los Angeles International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/katl_twr"
title = "KATL Tower"
artist = "Hartsfield-Jackson Atlanta"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/ksfo_twr"
title = "KSFO Tower"
artist = "San Francisco International"
album = "Live ATC"
genre = "ATC"
realtime = true
[[track]]
path = "http://d.liveatc.net/ksfo_atis"
title = "KSFO ATIS"
artist = "San Francisco International"
album = "Live ATC"
genre = "ATIS"
realtime = true
